// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetByUsername(ctx context.Context, name string) (GetByUsernameRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
