// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSite(ctx context.Context, arg CreateSiteParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteSite(ctx context.Context, arg DeleteSiteParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveSitesByStatus(ctx context.Context, status *string) ([]Site, error)
	GetAllSites(ctx context.Context) ([]Site, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetByID(ctx context.Context, id uuid.UUID) (GetByIDRow, error)
	GetByUserID(ctx context.Context, userID uuid.UUID) ([]Site, error)
	GetByUsername(ctx context.Context, name string) (GetByUsernameRow, error)
	GetSiteByID(ctx context.Context, id uuid.UUID) (Site, error)
	GetSiteStats(ctx context.Context, userID uuid.UUID) (GetSiteStatsRow, error)
	GetSitesNeedingCheck(ctx context.Context, limit int32) ([]Site, error)
	UpdateSiteStatus(ctx context.Context, arg UpdateSiteStatusParams) (UpdateSiteStatusRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
