// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id
`

type CreateSiteParams struct {
	Url                  string             `json:"url"`
	Name                 string             `json:"name"`
	CheckIntervalSeconds int32              `json:"check_interval_seconds"`
	UserID               uuid.UUID          `json:"user_id"`
	Status               *string            `json:"status"`
	LastStatusCode       *int32             `json:"last_status_code"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	ResponseTimeMs       *int32             `json:"response_time_ms"`
	IsActive             *bool              `json:"is_active"`
	VerifiedAt           pgtype.Timestamptz `json:"verified_at"`
	VerificationToken    *string            `json:"verification_token"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.Url,
		arg.Name,
		arg.CheckIntervalSeconds,
		arg.UserID,
		arg.Status,
		arg.LastStatusCode,
		arg.LastCheckedAt,
		arg.ResponseTimeMs,
		arg.IsActive,
		arg.VerifiedAt,
		arg.VerificationToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1 AND user_id = $2
`

type DeleteSiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) error {
	_, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.UserID)
	return err
}

const getActiveSitesByStatus = `-- name: GetActiveSitesByStatus :many
SELECT 
    id,
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
FROM sites 
WHERE is_active = true AND status = $1
`

func (q *Queries) GetActiveSitesByStatus(ctx context.Context, status *string) ([]Site, error) {
	rows, err := q.db.Query(ctx, getActiveSitesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.CheckIntervalSeconds,
			&i.UserID,
			&i.Status,
			&i.LastStatusCode,
			&i.LastCheckedAt,
			&i.ResponseTimeMs,
			&i.IsActive,
			&i.VerifiedAt,
			&i.VerificationToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSites = `-- name: GetAllSites :many
SELECT id,
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
FROM sites ORDER BY created_at DESC
`

func (q *Queries) GetAllSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, getAllSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.CheckIntervalSeconds,
			&i.UserID,
			&i.Status,
			&i.LastStatusCode,
			&i.LastCheckedAt,
			&i.ResponseTimeMs,
			&i.IsActive,
			&i.VerifiedAt,
			&i.VerificationToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByUserID = `-- name: GetByUserID :many
SELECT id,
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
FROM sites WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetByUserID(ctx context.Context, userID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, getByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.CheckIntervalSeconds,
			&i.UserID,
			&i.Status,
			&i.LastStatusCode,
			&i.LastCheckedAt,
			&i.ResponseTimeMs,
			&i.IsActive,
			&i.VerifiedAt,
			&i.VerificationToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id,
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
FROM sites WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.CheckIntervalSeconds,
		&i.UserID,
		&i.Status,
		&i.LastStatusCode,
		&i.LastCheckedAt,
		&i.ResponseTimeMs,
		&i.IsActive,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteStats = `-- name: GetSiteStats :one
SELECT 
    COUNT(*) as total_sites,
    COUNT(CASE WHEN status = 'up' THEN 1 END) as up_sites,
    COUNT(CASE WHEN status = 'down' THEN 1 END) as down_sites,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_sites,
    AVG(response_time_ms) as avg_response_time
FROM sites 
WHERE user_id = $1
`

type GetSiteStatsRow struct {
	TotalSites      int64   `json:"total_sites"`
	UpSites         int64   `json:"up_sites"`
	DownSites       int64   `json:"down_sites"`
	PendingSites    int64   `json:"pending_sites"`
	AvgResponseTime float64 `json:"avg_response_time"`
}

func (q *Queries) GetSiteStats(ctx context.Context, userID uuid.UUID) (GetSiteStatsRow, error) {
	row := q.db.QueryRow(ctx, getSiteStats, userID)
	var i GetSiteStatsRow
	err := row.Scan(
		&i.TotalSites,
		&i.UpSites,
		&i.DownSites,
		&i.PendingSites,
		&i.AvgResponseTime,
	)
	return i, err
}

const getSitesNeedingCheck = `-- name: GetSitesNeedingCheck :many
SELECT 
    id,
    url,
    name,
    check_interval_seconds,
    user_id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    is_active,
    verified_at,
    verification_token,
    created_at,
    updated_at
FROM sites 
WHERE is_active = true 
  AND (
    last_checked_at IS NULL 
    OR last_checked_at < NOW() - (check_interval_seconds * INTERVAL '1 second')
  )
ORDER BY last_checked_at NULLS FIRST
LIMIT $1
`

func (q *Queries) GetSitesNeedingCheck(ctx context.Context, limit int32) ([]Site, error) {
	rows, err := q.db.Query(ctx, getSitesNeedingCheck, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.CheckIntervalSeconds,
			&i.UserID,
			&i.Status,
			&i.LastStatusCode,
			&i.LastCheckedAt,
			&i.ResponseTimeMs,
			&i.IsActive,
			&i.VerifiedAt,
			&i.VerificationToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteStatus = `-- name: UpdateSiteStatus :one
UPDATE sites
SET 
    status = COALESCE($1, status),
    last_status_code = COALESCE($2, last_status_code),
    last_checked_at = COALESCE($3, last_checked_at),
    response_time_ms = COALESCE($4, response_time_ms),
    updated_at = NOW()
WHERE id = $5
RETURNING 
    id,
    status,
    last_status_code,
    last_checked_at,
    response_time_ms,
    updated_at
`

type UpdateSiteStatusParams struct {
	Status         *string            `json:"status"`
	LastStatusCode *int32             `json:"last_status_code"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	ResponseTimeMs *int32             `json:"response_time_ms"`
	ID             uuid.UUID          `json:"id"`
}

type UpdateSiteStatusRow struct {
	ID             uuid.UUID          `json:"id"`
	Status         *string            `json:"status"`
	LastStatusCode *int32             `json:"last_status_code"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	ResponseTimeMs *int32             `json:"response_time_ms"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSiteStatus(ctx context.Context, arg UpdateSiteStatusParams) (UpdateSiteStatusRow, error) {
	row := q.db.QueryRow(ctx, updateSiteStatus,
		arg.Status,
		arg.LastStatusCode,
		arg.LastCheckedAt,
		arg.ResponseTimeMs,
		arg.ID,
	)
	var i UpdateSiteStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.LastStatusCode,
		&i.LastCheckedAt,
		&i.ResponseTimeMs,
		&i.UpdatedAt,
	)
	return i, err
}
