// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    telegram_id,
    password_hash,
    role,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type CreateUserParams struct {
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	TelegramID   int64              `json:"telegram_id"`
	PasswordHash *string            `json:"password_hash"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.TelegramID,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id,
    email,
    name,
    telegram_id,
    password_hash,
    role,
    created_at,
    updated_at
FROM users ORDER BY created_at DESC
`

type GetAllUsersRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	TelegramID   int64              `json:"telegram_id"`
	PasswordHash *string            `json:"password_hash"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.TelegramID,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id,
    email,
    name,
    telegram_id,
    password_hash,
    role,
    created_at,
    updated_at
FROM users WHERE id = $1 ORDER BY created_at DESC
`

type GetByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	TelegramID   int64              `json:"telegram_id"`
	PasswordHash *string            `json:"password_hash"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByUsername = `-- name: GetByUsername :one
SELECT id,
    email,
    name,
    telegram_id,
    password_hash,
    role,
    created_at,
    updated_at
FROM users WHERE name = $1 ORDER BY created_at DESC
`

type GetByUsernameRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	TelegramID   int64              `json:"telegram_id"`
	PasswordHash *string            `json:"password_hash"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetByUsername(ctx context.Context, name string) (GetByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getByUsername, name)
	var i GetByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TelegramID,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    email = COALESCE($1, email),
    name = COALESCE($2, name),
    password_hash = COALESCE($3, password_hash),
    role = COALESCE($4, role),
    updated_at = NOW()
WHERE id = $5
RETURNING id
`

type UpdateUserParams struct {
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash *string   `json:"password_hash"`
	Role         *string   `json:"role"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
